#
# This file is part of the PrintFlowLite project <https://www.PrintFlowLite.org>.
# Copyright (c) 2011-2025 Datraverse B.V.
# Author: Rijk Ravestein.
#
# SPDX-FileCopyrightText: 2011-2025 Datraverse B.V. <info@datraverse.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# For more information, please contact Datraverse B.V. at this
# address: info@datraverse.com
#

#=======================================================================
# PrintFlowLite Logging Properties Template
#=======================================================================

### log messages to stdout ###
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} %5p %c{1}:%L - %m [%t]%n
log4j.appender.stdout.encoding=UTF8

### log messages to file  ###
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.MaxFileSize=10MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.File=${server.home}/logs/server.log
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{ISO8601} %5p %c{1}:%L - %m [%t]%n
log4j.appender.file.encoding=UTF8

#### default server mode
log4j.rootLogger=ERROR, file

#### developer mode
# log4j.rootLogger=ERROR, file, stdout

#### Application Logging ####
log4j.logger.org.printflow.lite=WARN
log4j.logger.org.printflow.lite.core.SpInfo=INFO

#------------------------------------------------------------------------------
# Suppress WARN and ERROR messages caused by Opera browser
#------------------------------------------------------------------------------
log4j.logger.org.apache.wicket.DefaultExceptionMapper=FATAL

#------------------------------------------------------------------------------
# Security Logger
#------------------------------------------------------------------------------
log4j.appender.securitylogger=org.apache.log4j.RollingFileAppender
log4j.appender.securitylogger.MaxFileSize=10MB
log4j.appender.securitylogger.MaxBackupIndex=10
log4j.appender.securitylogger.File=${server.home}/logs/security.log
log4j.appender.securitylogger.layout=org.apache.log4j.PatternLayout
log4j.appender.securitylogger.layout.ConversionPattern=%m\n
log4j.appender.securitylogger.encoding=UTF8

# Use INFO to activate the SecurityLogger
log4j.logger.org.printflow.lite.server.SecurityLogger=INFO, securitylogger
log4j.additivity.org.printflow.lite.server.SecurityLogger=false

#------------------------------------------------------------------------------
# Performance Logger
#------------------------------------------------------------------------------
log4j.appender.performancelogger=org.apache.log4j.RollingFileAppender
log4j.appender.performancelogger.MaxFileSize=10MB
log4j.appender.performancelogger.MaxBackupIndex=10
log4j.appender.performancelogger.File=${server.home}/logs/perf.log
log4j.appender.performancelogger.layout=org.apache.log4j.PatternLayout
log4j.appender.performancelogger.layout.ConversionPattern=%m\n
log4j.appender.performancelogger.encoding=UTF8

# Use TRACE to activate the PerformanceLogger
log4j.logger.org.printflow.lite.core.PerformanceLogger=ERROR, performancelogger
log4j.additivity.org.printflow.lite.core.PerformanceLogger=false

#------------------------------------------------------------------------------
# AdminPublisher Logger
#------------------------------------------------------------------------------
log4j.appender.adminpublisher=org.apache.log4j.RollingFileAppender
log4j.appender.adminpublisher.MaxFileSize=10MB
log4j.appender.adminpublisher.MaxBackupIndex=10
log4j.appender.adminpublisher.File=${server.home}/logs/adminpublisher.log
log4j.appender.adminpublisher.layout=org.apache.log4j.PatternLayout
log4j.appender.adminpublisher.layout.ConversionPattern=%m\n
log4j.appender.adminpublisher.encoding=UTF8

# Use INFO to activate the AdminPublisher
log4j.logger.org.printflow.lite.core.cometd.AdminPublisherLogger=INFO, adminpublisher
log4j.additivity.org.printflow.lite.core.cometd.AdminPublisherLogger=false

#------------------------------------------------------------------------------
# ProxyPrint Logger
#------------------------------------------------------------------------------
log4j.appender.proxyprint=org.apache.log4j.RollingFileAppender
log4j.appender.proxyprint.MaxFileSize=10MB
log4j.appender.proxyprint.MaxBackupIndex=10
log4j.appender.proxyprint.File=${server.home}/logs/proxy-print.log
log4j.appender.proxyprint.layout=org.apache.log4j.PatternLayout
log4j.appender.proxyprint.layout.ConversionPattern=%d{ISO8601} : %m%n%n
log4j.appender.proxyprint.encoding=UTF8

# Use INFO to activate the ProxyPrint Logger
log4j.logger.org.printflow.lite.core.print.proxy.ProxyPrintLogger=INFO, proxyprint
log4j.additivity.org.printflow.lite.core.print.proxy.ProxyPrintLogger=false

#------------------------------------------------------------------------------
# Payment Gateway Audit Trail
#------------------------------------------------------------------------------
log4j.appender.paymentgateway=org.apache.log4j.RollingFileAppender
log4j.appender.paymentgateway.MaxFileSize=10MB
log4j.appender.paymentgateway.MaxBackupIndex=10
log4j.appender.paymentgateway.File=${server.home}/logs/paymentgateway.log
log4j.appender.paymentgateway.layout=org.apache.log4j.PatternLayout
log4j.appender.paymentgateway.layout.ConversionPattern=%m\n
log4j.appender.paymentgateway.encoding=UTF8

# Use INFO to activate the PaymentGatewayLogger
log4j.logger.org.printflow.lite.server.ext.PaymentGatewayLogger=INFO, paymentgateway
log4j.additivity.org.printflow.lite.server.ext.PaymentGatewayLogger=false

#------------------------------------------------------------------------------
# Add custom logging below as instructed by PrintFlowLite Support
#------------------------------------------------------------------------------

# end-of-file
