/*
 * This file is part of the PrintFlowLite project <https://printflowlite.local>.
 * Copyright (c) 2021 Datraverse B.V.
 * Author: Rijk Ravestein.
 *
 * SPDX-FileCopyrightText: © 2021 Datraverse B.V. <info@datraverse.com>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For more information, please contact Datraverse B.V. at this
 * address: info@datraverse.com
 */
package org.printflow.lite.common;

/**
 * Encapsulation of Java system properties.
 *
 * @author Rijk Ravestein
 *
 */
public enum SystemPropertyEnum {

    /**
     * Location of derby log file.
     *
     * See <a href=
     * "https://docs.oracle.com/javadb/10.8.1.2/ref/crefproper22250.html">Derby
     * properties</a>.
     */
    DERBY_STREAM_ERROR_FILE("derby.stream.error.file"),

    /**
     * See <a href=
     * "https://docs.oracle.com/javadb/10.8.1.2/ref/crefproper22250.html">Derby
     * properties</a>.
     */
    DERBY_DEADLOCK_TIMEOUT("derby.locks.deadlockTimeout"),

    /**
     * See <a href=
     * "https://docs.oracle.com/javadb/10.8.1.2/ref/crefproper22250.html">Derby
     * properties</a>.
     */
    DERBY_LOCKS_WAITTIMEOUT("derby.locks.waitTimeout"),

    /**
     * Character that separates components of a file path. This is "/" on UNIX
     * and "\" on Windows.
     */
    FILE_SEPARATOR("file.separator"),

    /**
     * Path used to find directories and JAR archives containing class files.
     * Elements of the class path are separated by a platform-specific character
     * specified in the path.separator property.
     */
    JAVA_CLASS_PATH("java.class.path"),

    /**
     * Installation directory for Java Runtime Environment (JRE).
     */
    JAVA_HOME("java.home"),

    /**
     * Default temporary file location.
     */
    JAVA_IO_TMPDIR("java.io.tmpdir"),

    /**
     * JRE vendor name.
     */
    JAVA_VENDOR("java.vendor"),

    /**
     * JRE vendor URL.
     */
    JAVA_VENDOR_URL("java.vendor.url"),

    /**
     * JRE version number.
     */
    JAVA_VERSION("java.version"),

    /**
     * Java VM name.
     */
    JAVA_VM_NAME("java.vm.name"),

    /**
     * Sequence used by operating system to separate lines in text files.
     */
    LINE_SEPARATOR("line.separator"),

    /**
     * Path of log4j configuration file (log4j.properties).
     */
    LOG4J_CONFIGURATION("log4j.configuration"),

    /**
     * Application home directory generated by the Maven
     * {@code appassembler-maven-plugin}.
     */
    MAVEN_APPASSEMBLER_HOME("app.home"),

    /**
     * Application name generated by the Maven
     * {@code appassembler-maven-plugin}.
     */
    MAVEN_APPASSEMBLER_NAME("app.name"),

    /**
     * Application PID generated by the Maven {@code appassembler-maven-plugin}.
     */
    MAVEN_APPASSEMBLER_PID("app.pid"),

    /**
     * Repository home (containing dependent .jar files) generated by the Maven
     * {@code appassembler-maven-plugin}.
     */
    MAVEN_APPASSEMBLER_REPO("app.repo"),

    /**
     * Operating system architecture.
     */
    OS_ARCH("os.arch"),

    /**
     * Operating system name.
     */
    OS_NAME("os.name"),

    /**
     * Operating system version.
     */
    OS_VERSION("os.version"),

    /**
     * Path separator character used in java.class.path.
     */
    PATH_SEPARATOR("path.separator"),

    /**
     * PrintFlowLite server home directory.
     */
    PRINTFLOWLITE_SERVER_HOME("server.home"),

    /**
     * PrintFlowLite client home directory.
     */
    PRINTFLOWLITE_CLIENT_HOME("client.home"),

    /**
     * PrintFlowLite WAR filename.
     */
    PRINTFLOWLITE_WAR_FILE("printflowlite.war.file"),
    /**
     * Location of OpenOffice or LibreOffice package. This can be passed as VM
     * argument, for instance:
     * <p>
     * {@code -Dsoffice.home=/usr/lib/libreoffice}
     * </p>
     */
    SOFFICE_HOME("soffice.home"),

    /**
     * User working directory.
     */
    USER_DIR("user.dir"),

    /**
     * User home directory.
     */
    USER_HOME("user.home"),

    /**
     * User account name.
     */
    USER_NAME("user.name");

    /**
     * Property key.
     */
    private final String key;

    /**
     * @param k
     *            Property key.
     */
    SystemPropertyEnum(final String k) {
        this.key = k;
    }

    /**
     * @return Key of this system property.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * @return String value of the system property, or null if there is no
     *         property with that key.
     */
    public String getValue() {
        return System.getProperty(this.key);
    }

    /**
     * Sets the system property value.
     *
     * @param value
     *            the value of the system property.
     */
    public void setValue(final String value) {
        setValue(this.key, value);
    }

    /**
     * Sets the system property value.
     *
     * @param key
     *            the key of the system property.
     * @param value
     *            the value of the system property.
     */
    public static void setValue(final String key, final String value) {
        System.setProperty(key, value);
    }
}
