webapp-title-suffix=PrintFlowLite
sys-status-setup-needed=Setup Needed
sys-status-not-available=Not Available
sys-status-ready=Ready
membership-status-exceeded=Account balance exceeded
membership-status-expired=Membership expired
membership-status-wrong=Wrong card or PIN
txt-logo-subtext=Administration
txt-welcome-salutation=Welcome
txt-welcome=Manage your PrintFlowLite server
button-logout=Logout
button-top=Top
button-menu=Menu
